### ISSUE TITLE
Homework Work Load

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-intro-marleyhaupt1#2]
Hello Will,

I have been working on the assigned exercises and it has been taking me a long time. I want to make sure that I do them properly, but I think there is a good chance that I could fall behind at the rate I am currently plugging along. Are we going to continue to receive this level of homework load throughout the rest of the course? And if so, do you have any suggestions for doing the homework (correctly) in a timely manner?

Sorry to ask. I'm sure these types of questions are an instructors least favorite. I swear I'm not trying to be whiney!

Marley

**Comment by willpearse** [comment]
Thanks for this Marley. Please don't be concerned: I will be taking steps to address some of the workload issues you've all been mentioning in the next session.

My advice for the time being is to jump around a bit. Don't bash your head against the questions from session 2 that are difficult: move on to session 3 and see what you can do in there that is easier. You will almost certainly find session 2 easier once you've done parts of session 3.

**Comment by marleyhaupt1** [comment]
Thanks for answering my question. I appreciate your help!
