### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-intro-marleyhaupt1#7]
Hello Will,

I know that we aren't required to do the bonus exercises, but I would like to try to figure out how to do the regular expressions exercise (Session 1, Bonus Exercise 1.8). Last semester I had to write a regular expression for a piece of code that identified and separating out individual plants based on unique identifiers (i.e. every unique plant ID began with @ and was followed by numbers, lower case letters, and/or uppercase letters) The script then took the ID of each plant and all the information following until the next plant ID and created a new file. Needless to say, I screwed the expression up.

I understand a little tiny bit about how regular expressions work, but since I will undoubtedly run into regular expressions again in my schooling/career I would like to figure them out. I have been reading some tutorials on http://www.regular-expressions.info/tutorial.html but I was wondering if I could sit down with you sometime and get some more help?

Thanks!
Marley

**Comment by willpearse** [comment]
Sure. Is there a time on Wednesday or later during the week that works for you?

**Comment by marleyhaupt1** [comment]
Sure. How is Thursday for you? I can meet anytime that day.

On Jan 13, 2017 5:47 PM, "Will Pearse" <notifications@github.com> wrote:

Sure. Is there a time on Wednesday or later during the week that works for
you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pearselab/r-intro-marleyhaupt1/issues/7#issuecomment-272586172>,
or mute the thread

**Comment by willpearse** [comment]
Great. I'll see you at 1pm on Thursday.

**Comment by marleyhaupt1** [comment]
Hi Will! Would it be ok if we pushed our meeting time back half an hour to 1:30? I had something come up and I’m not sure if I will be done in time to make it at 1. Sorry!

**Comment by willpearse** [comment]
I'm meeting another student at 2pm, so it might make things a bit tricky.
I'm free right now if you just come into my office...

**Comment by marleyhaupt1** [comment]
I’m actually out of town for a wedding until tomorrow night, but I will just make sure to keep my earlier meeting short. I’ll make sure I am there at 1. Thanks again. Sorry for the confusion!

**Comment by willpearse** [comment]
No worries. If you're late that's fine; I don't think our meeting will take
long to be honest.

**Comment by marleyhaupt1** [comment]
Yeah, I don’t really think it will either. Thanks for being flexible. I appreciate it.
