### ISSUE TITLE
Help with New.Polygon

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-intro-marleyhaupt1#8]
Howdy Will,

I have been working on the exercises for R Intro Session 3, and I think I need a bit of help with #5. I want to be able to input as many point class arguments as I want into a polygon class and I am not sure how to do this (do you use .... ?). Also, I want polygon classes to be formatted similarly to the format of my point and line classes (a list containing all of the x and y coordinates). Example:

> line1
$x1
[1] 4

$y1
[1] 7

$x2
[1] 3

$y2
[1] -2

attr(,"class")
[1] "line"

I have tried messing around with this for about an hour and I feel like I am just going around in circles. Any suggestions?

Thanks,
Marley

**Comment by willpearse** [comment]
Probably best if you pop in and have a chat with me. Object orientation is
easy once you know how, but everyone needs to talk about it in my
experience.

You don't need to make it work for arbitrary numbers of lines, but if you
swing by my office I will show you that too. It does involve ... - you're
correct.

**Comment by marleyhaupt1** [comment]
That would be great. Is there a time that works best for you? I can swing by anytime today, tomorrow, or Thursday.
Thanks for helping me with this!
Marley

**Comment by willpearse** [comment]
Come by this afternoon, say... 1pm?

**Comment by marleyhaupt1** [comment]
Sounds great. Thanks Will
